name: Remote Dispatch Action

permissions:
  contents: write
  pull-requests: write

# ───────────────────────────── TRIGGERS ─────────────────────────────
on:
  repository_dispatch:

  workflow_dispatch:
    inputs:
      component:
        description: "Component (gardenlogin | gardenctl-v2 | diki)"
        required: true
        type: string
      tag:
        description: "Version / tag (e.g. v1.4.0)"
        required: true
        type: string
      windows_sha:
        description: "Optional sha256 for the Windows binary"
        required: false
        type: string
      push_to_chocolatey:
        description: "true → push .nupkg (default false = dry-run)"
        type: boolean
        default: false

##############################################################################
# 1) COMMON PRE-FLIGHT (compute numeric version once)
##############################################################################
jobs:
  package-push-common:
    runs-on: windows-latest
    outputs:
      cleaned_version: ${{ steps.extract.outputs.cleaned }}

    env:
      TAG: ${{ github.event_name == 'repository_dispatch'
                && github.event.client_payload.tag
                || inputs.tag }}

    steps:
      - name: Show incoming payload
        run: |
          echo "Trigger       : ${{ github.event_name }}"
          echo "Component     : ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.component || inputs.component }}"
          echo "Tag           : ${{ env.TAG }}"
          echo "windows_sha   : ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.windows_sha || inputs.windows_sha }}"

      - name: Extract numeric version
        id: extract
        shell: pwsh
        run: |
          $clean = "${{ env.TAG }}".Replace('v','')
          echo "cleaned=$clean" >> $env:GITHUB_OUTPUT

##############################################################################
# 2) MATRIX JOB – ONE ROW, FILTERED BY job-level if:
##############################################################################
  package-push:
    runs-on: windows-latest
    needs: package-push-common

    strategy:
      matrix:
        include:
          - component: gardenlogin
            script: .github\workflows\update-gardenlogin.ps1
            nuspec: gardenlogin\gardenlogin.nuspec
            pkg_dir: gardenlogin
            pkg_name: gardenlogin
            skip_var: SKIP_CHOCO_PUSH_GARDENLOGIN
            extra_paths:
              - gardenlogin\tools\chocolateyinstall.ps1
              - gardenlogin\tools\chocolateyuninstall.ps1

          - component: gardenctl-v2
            script: .github\workflows\update-gardenctl-v2.ps1
            nuspec: gardenctl-v2\gardenctl-v2.nuspec
            pkg_dir: gardenctl-v2
            pkg_name: gardenctl-v2
            skip_var: SKIP_CHOCO_PUSH_GARDENCTL_V2
            extra_paths:
              - gardenctl-v2\tools\chocolateyinstall.ps1

          - component: diki
            script: .github\workflows\update-diki.ps1
            nuspec: diki\diki.nuspec
            pkg_dir: diki
            pkg_name: diki
            skip_var: SKIP_CHOCO_PUSH_DIKI
            extra_paths:
              - diki\tools\chocolateyinstall.ps1

    # only run this job if the component matches the event payload or input
    if: ${{ matrix.component ==
            (github.event_name == 'repository_dispatch'
              && github.event.client_payload.component
              || inputs.component) }}

    env:
      NUM_VERSION: ${{ needs.package-push-common.outputs.cleaned_version }}
      FULL_TAG:    ${{ github.event_name == 'repository_dispatch'
                       && github.event.client_payload.tag
                       || inputs.tag }}
      WINDOWS_SHA: ${{ github.event_name == 'repository_dispatch'
                       && github.event.client_payload.windows_sha
                       || inputs.windows_sha
                       || 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855' }}
      EXTRA_PATHS: ${{ join(matrix.extra_paths, ' ') }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Update nuspec & install scripts
        shell: pwsh
        run: |
          & "${{ matrix.script }}" `
            "${{ env.FULL_TAG }}" `
            "${{ env.WINDOWS_SHA }}"

      # ─────────────── pack ───────────────
      - name: Choco pack
        shell: pwsh
        run: |
          choco pack ${{ matrix.nuspec }} `
                     --version ${{ env.NUM_VERSION }} `
                     -y --outdir ${{ matrix.pkg_dir }}

      # ─────────────── push (optional) ────
      - name: Choco push
        if: ${{ vars[matrix.skip_var] != 'true' &&
                (github.event_name == 'repository_dispatch' ||
                 inputs.push_to_chocolatey == true) }}
        shell: pwsh
        env:
          CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
        run: |
          choco push "${{ matrix.pkg_dir }}\${{ matrix.pkg_name }}.${{ env.NUM_VERSION }}.nupkg" `
                     --source https://chocolatey.org `
                     -k $Env:CHOCOLATEY_API_KEY

      - name: Choco push skipped
        if: ${{ vars[matrix.skip_var] == 'true' ||
                (github.event_name == 'workflow_dispatch' && inputs.push_to_chocolatey != true) }}
        run: echo "Push skipped for ${{ matrix.component }}."

      # ─────────────── PR creation ────────
      - name: Create pull request
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          branch="update_${{ matrix.component }}_${{ env.FULL_TAG }}"
          git switch -c "$branch"
          git add "${{ matrix.pkg_dir }}\\${{ matrix.pkg_name }}.${{ env.NUM_VERSION }}.nupkg"
          git add "${{ matrix.nuspec }}"
          for p in ${EXTRA_PATHS}; do git add "$p"; done
          git commit -m "update ${{ matrix.component }} to ${{ env.FULL_TAG }}"
          git push --force-with-lease -u origin "$branch"

          gh pr create \
            --head "$branch" \
            --base "${{ github.event.repository.default_branch }}" \
            --title "update ${{ matrix.component }} to ${{ env.FULL_TAG }}" \
            --body  "This PR adds/updates the Chocolatey package for **${{ matrix.component }}** (${ env.FULL_TAG })."
