name: Remote Dispatch Action
on: [repository_dispatch]
permissions:
  contents: write
  packages: write
jobs:
  package-push-common:
    runs-on: windows-latest
    outputs:
      cleaned_version: ${{ steps.get_version.outputs.cleaned_version }}
    steps:
      - name: Event Information
        id: event_info
        run: |
          echo "Event '${{ github.event.action }}' payload '${{ github.event.client_payload.tag }}'"
          echo "Windows binary hash '${{ github.event.client_payload.windows_sha }}'"
      - name: Get Version
        id: get_version
        run: |
          $version="${{ github.event.client_payload.tag }}"
          $cleaned_version=$version.replace('v','')
          echo "cleaned_version=$cleaned_version" >> $env:GITHUB_OUTPUT
  package-push-gardenlogin:
    if: github.event.client_payload.component == 'gardenlogin'
    runs-on: windows-latest
    needs: package-push-common
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
      - name: Update package source files
        run: .github\workflows\update-gardenlogin.ps1 ${{ github.event.client_payload.tag }} ${{ github.event.client_payload.windows_sha }}
      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@6828f16489ec8d2968b55066766cb41f0d278f2a # pin@v3.3.0
        with:
          args: pack gardenlogin\gardenlogin.nuspec --version=${{ needs.package-push-common.outputs.cleaned_version }} -y --outdir gardenlogin
      - name: Choco push
        if: ${{ vars.SKIP_CHOCO_PUSH_GARDENLOGIN != 'true' }}
        uses: crazy-max/ghaction-chocolatey@6828f16489ec8d2968b55066766cb41f0d278f2a # pin@v3.3.0
        with:
          args: push "gardenlogin\gardenlogin.${{ needs.package-push-common.outputs.cleaned_version }}.nupkg" --source https://chocolatey.org -k ${{ secrets.CHOCOLATEY_API_KEY }}
      - name: Choco push - print skip info
        if: ${{ vars.SKIP_CHOCO_PUSH_GARDENLOGIN == 'true' }}
        run: echo "Choco push step was skipped for package-push-gardenlogin."
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # pin@v7.0.8
        with:
          add-paths: gardenlogin\gardenlogin.${{ needs.package-push-common.outputs.cleaned_version }}.nupkg,gardenlogin\tools\chocolateyinstall.ps1,gardenlogin\tools\chocolateyuninstall.ps1
          branch: update_${{ github.event.client_payload.component }}_${{ github.event.client_payload.tag }}
          delete-branch: true
          title: update ${{ github.event.client_payload.component }} to ${{ github.event.client_payload.tag }}
          body: This PR adds Chocolatey package for version ${{ github.event.client_payload.tag }} and updates package sources
  package-push-gardenctl-v2:
    if: github.event.client_payload.component == 'gardenctl-v2'
    runs-on: windows-latest
    needs: package-push-common
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
      - name: Update package source files
        run: .github\workflows\update-gardenctl-v2.ps1 ${{ github.event.client_payload.tag }} ${{ github.event.client_payload.windows_sha }}
      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@6828f16489ec8d2968b55066766cb41f0d278f2a # pin@v3.3.0
        with:
          args: pack gardenctl-v2\gardenctl-v2.nuspec --version=${{ needs.package-push-common.outputs.cleaned_version }} -y --outdir gardenctl-v2
      - name: Choco push
        if: ${{ vars.SKIP_CHOCO_PUSH_GARDENCTL_V2 != 'true' }}
        uses: crazy-max/ghaction-chocolatey@6828f16489ec8d2968b55066766cb41f0d278f2a # pin@v3.3.0
        with:
          args: push "gardenctl-v2\gardenctl-v2.${{ needs.package-push-common.outputs.cleaned_version }}.nupkg" --source https://chocolatey.org -k ${{ secrets.CHOCOLATEY_API_KEY }}
      - name: Choco push - print skip info
        if: ${{ vars.SKIP_CHOCO_PUSH_GARDENCTL_V2 == 'true' }}
        run: echo "Choco push step was skipped for package-push-gardenctl-v2."
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # pin@v7.0.8
        with:
          add-paths: gardenctl-v2\gardenctl-v2.${{ needs.package-push-common.outputs.cleaned_version }}.nupkg,gardenctl-v2\tools\chocolateyinstall.ps1
          branch: update_${{ github.event.client_payload.component }}_${{ github.event.client_payload.tag }}
          delete-branch: true
          title: update ${{ github.event.client_payload.component }} to ${{ github.event.client_payload.tag }}
          body: This PR adds Chocolatey package for version ${{ github.event.client_payload.tag }} and updates package sources
  package-push-diki:
    if: github.event.client_payload.component == 'diki'
    runs-on: windows-latest
    needs: package-push-common
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
      - name: Update package source files
        run: .github\workflows\update-diki.ps1 ${{ github.event.client_payload.tag }} ${{ github.event.client_payload.windows_sha }}
      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@6828f16489ec8d2968b55066766cb41f0d278f2a # pin@v3.3.0
        with:
          args: pack diki\diki.nuspec --version=${{ needs.package-push-common.outputs.cleaned_version }} -y --outdir diki
      - name: Choco push
        if: ${{ vars.SKIP_CHOCO_PUSH_DIKI != 'true' }}
        uses: crazy-max/ghaction-chocolatey@6828f16489ec8d2968b55066766cb41f0d278f2a # pin@v3.3.0
        with:
          args: push "diki\diki.${{ needs.package-push-common.outputs.cleaned_version }}.nupkg" --source https://chocolatey.org -k ${{ secrets.CHOCOLATEY_API_KEY }}
      - name: Choco push - print skip info
        if: ${{ vars.SKIP_CHOCO_PUSH_DIKI == 'true' }}
        run: echo "Choco push step was skipped for package-push-diki."
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # pin@v7.0.8
        with:
          add-paths: diki\diki.${{ needs.package-push-common.outputs.cleaned_version }}.nupkg,diki\tools\chocolateyinstall.ps1
          branch: update_${{ github.event.client_payload.component }}_${{ github.event.client_payload.tag }}
          delete-branch: true
          title: update ${{ github.event.client_payload.component }} to ${{ github.event.client_payload.tag }}
          body: This PR adds Chocolatey package for version ${{ github.event.client_payload.tag }} and updates package sources
