name: Remote Dispatch Action
on: [repository_dispatch]
jobs:
  package-push-common:
    runs-on: windows-latest
    outputs:
      cleaned_version: ${{ steps.get_version.outputs.cleaned_version }}
    steps:
      - name: Event Information
        id: event_info
        run: |
          echo "Event '${{ github.event.action }}' payload '${{ github.event.client_payload.tag }}'"
          echo "Windows binary hash '${{ github.event.client_payload.windows_sha }}'"
      - name: Get Version
        id: get_version
        run: |
          $version="${{ github.event.client_payload.tag }}"
          $cleaned_version=$version.replace('v','')
          echo "cleaned_version=$cleaned_version" >> $env:GITHUB_OUTPUT
  package-push-gardenlogin:
    if: github.event.client_payload.component == 'gardenlogin'
    runs-on: windows-latest
    needs: package-push-common
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4.2.1
      - name: Update package source files
        run: .github\workflows\update-gardenlogin.ps1 ${{ github.event.client_payload.tag }} ${{ github.event.client_payload.windows_sha }}
      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@0e015857dd851f84fcb7fb53380eb5c4c8202333 # pin@v3.0.0
        with:
          args: pack gardenlogin\gardenlogin.nuspec --version=${{ needs.package-push-common.outputs.cleaned_version }} -y --outdir gardenlogin
      - name: Choco push
        if: ${{ vars.SKIP_CHOCO_PUSH_GARDENLOGIN != 'true' }}
        uses: crazy-max/ghaction-chocolatey@0e015857dd851f84fcb7fb53380eb5c4c8202333 # pin@v3.0.0
        with:
          args: push "gardenlogin\gardenlogin.${{ needs.package-push-common.outputs.cleaned_version }}.nupkg" --source https://chocolatey.org -k ${{ secrets.CHOCOLATEY_API_KEY }}
      - name: Choco push - print skip info
        if: ${{ vars.SKIP_CHOCO_PUSH_GARDENLOGIN == 'true' }}
        run: echo "Choco push step was skipped for package-push-gardenlogin."
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # pin@v7.0.5
        with:
          add-paths: gardenlogin\gardenlogin.${{ needs.package-push-common.outputs.cleaned_version }}.nupkg,gardenlogin\tools\chocolateyinstall.ps1,gardenlogin\tools\chocolateyuninstall.ps1
          branch: update_${{ github.event.client_payload.component }}_${{ github.event.client_payload.tag }}
          delete-branch: true
          title: update ${{ github.event.client_payload.component }} to ${{ github.event.client_payload.tag }}
          body: This PR adds Chocolatey package for version ${{ github.event.client_payload.tag }} and updates package sources
  package-push-gardenctl-v2:
    if: github.event.client_payload.component == 'gardenctl-v2'
    runs-on: windows-latest
    needs: package-push-common
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # pin@v4.2.1
      - name: Update package source files
        run: .github\workflows\update-gardenctl-v2.ps1 ${{ github.event.client_payload.tag }} ${{ github.event.client_payload.windows_sha }}
      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@0e015857dd851f84fcb7fb53380eb5c4c8202333 # pin@v3.0.0
        with:
          args: pack gardenctl-v2\gardenctl-v2.nuspec --version=${{ needs.package-push-common.outputs.cleaned_version }} -y --outdir gardenctl-v2
      - name: Choco push
        if: ${{ vars.SKIP_CHOCO_PUSH_GARDENCTL_V2 != 'true' }}
        uses: crazy-max/ghaction-chocolatey@0e015857dd851f84fcb7fb53380eb5c4c8202333 # pin@v3.0.0
        with:
          args: push "gardenctl-v2\gardenctl-v2.${{ needs.package-push-common.outputs.cleaned_version }}.nupkg" --source https://chocolatey.org -k ${{ secrets.CHOCOLATEY_API_KEY }}
      - name: Choco push - print skip info
        if: ${{ vars.SKIP_CHOCO_PUSH_GARDENCTL_V2 == 'true' }}
        run: echo "Choco push step was skipped for package-push-gardenctl-v2."
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # pin@v7.0.5
        with:
          add-paths: gardenctl-v2\gardenctl-v2.${{ needs.package-push-common.outputs.cleaned_version }}.nupkg,gardenctl-v2\tools\chocolateyinstall.ps1
          branch: update_${{ github.event.client_payload.component }}_${{ github.event.client_payload.tag }}
          delete-branch: true
          title: update ${{ github.event.client_payload.component }} to ${{ github.event.client_payload.tag }}
          body: This PR adds Chocolatey package for version ${{ github.event.client_payload.tag }} and updates package sources
